// Embeds the vite build into convex/siteAssets.ts so the Convex deployment
// serves the SPA on its .convex.site domain via HTTP routes.
// Run through: npm run build:site
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const dist = join(root, "dist");

const CONTENT_TYPES = {
  html: "text/html; charset=utf-8",
  js: "text/javascript; charset=utf-8",
  css: "text/css; charset=utf-8",
  svg: "image/svg+xml",
  json: "application/json",
  png: "image/png",
  ico: "image/x-icon",
  txt: "text/plain; charset=utf-8",
  map: "application/json",
};

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) yield* walk(path);
    else yield path;
  }
}

const assets = {};
for (const path of walk(dist)) {
  const rel = "/" + relative(dist, path).replaceAll("\\", "/");
  const ext = rel.split(".").pop();
  const contentType = CONTENT_TYPES[ext];
  if (!contentType) {
    console.warn(`skipping ${rel}: unknown extension`);
    continue;
  }
  assets[rel] = { contentType, base64: readFileSync(path).toString("base64") };
}

const out = `// Generated by scripts/embed-site.mjs from the vite build. Do not edit.
export const SITE_ASSETS: Record<string, { contentType: string; base64: string }> = ${JSON.stringify(assets, null, 2)};
`;
writeFileSync(join(root, "convex", "siteAssets.ts"), out);
const total = Object.values(assets).reduce((n, a) => n + a.base64.length, 0);
console.log(
  `embedded ${Object.keys(assets).length} assets (${(total / 1024).toFixed(0)} KB base64) into convex/siteAssets.ts`,
);
